version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci

  build:
    commands:
      - npm run build

artifacts:
  files:
    - package.json
    - package-lock.json
    - Procfile
    - start.sh
    - .next/**/*
    - public/**/*
  discard-paths: no
