version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Installing dependencies…"
      - npm ci
      - echo "Building app…"
      - npm run build        # if you have a build step
      - echo "Packaging…"
      - zip -r deployment.zip * .[^.]*

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - deployment.zip
